version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - torch
        - torchvision
        - torchaudio
        - --extra-index-url https://download.pytorch.org/whl/cpu
        - dev
